# Generated by Django 4.1.2 on 2024-07-12 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_mensajesoporte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajesoporte',
            options={},
        ),
        migrations.RenameField(
            model_name='mensajesoporte',
            old_name='fecha_envio',
            new_name='fecha_creacion',
        ),
    ]
